name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  REPOSITORY: sample-nginx

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - id: commit
      uses: prompt/actions-commit-hash@v3    
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fscojr/nginx:$IMAGE_TAG
      env:
        IMAGE_TAG:  ${{ steps.commit.outputs.short }}

    - name: Build the Docker image
      run: docker push fscojr/nginx:$IMAGE_TAG
      env:
        IMAGE_TAG: ${{ steps.commit.outputs.short }}
    outputs:
      commit: ${{ steps.commit.outputs.short }}

  cid:
    env:
      IMAGE_TAG: ${{ needs.build.outputs.commit }}
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
      name: Checkout code app
      with:
        path: app-code

    - uses: actions/checkout@v4
      name: Checkout code charts
      with:
        repository: 'fscojr/apps-charts'
        path: apps-charts
        token: ${{ secrets.GIT_TOKEN }} 
    
    - name: Update Charts
      env:
        IMAGE_TAG: ${{ needs.build.outputs.commit }}
      run: echo $IMAGE_TAG

    - name: Change Image Ref.
      run:
        sed -i "s/#VERSION#/$IMAGE_TAG/g" app-code/.k8s/production.yml 
        cat app-code/.k8s/production.yml 

    - name: Create Chart
      run: |
        cd  app-code/.k8s/
        cat > Chart.yaml <<EOL
        apiVersion: v2
        dependencies:
        - name: firedev
          repository: file://../.helm/apps_templates
          version: 1.0.0
        description: FireDev apps
        name: $REPOSITORY
        version: $IMAGE_TAG
        EOL

    - name: Update file Chart
      run: | 
        mkdir -p  apps-charts/$REPOSITORY
        cp app-code/Chart.yaml apps-charts/$REPOSITORY/
        cp app-code/.k8s/production.yml 

    - name: Push  apps-charts
      run: |
        cd apps-charts
        ls -l 
        git config user.name "Devops"
        git config user.email "fscojr@github.com"
        git add .
        git commit -m "Update $REPOSITORY $IMAGE_TAG"
        git push
      


        
    
