name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - id: commit
      uses: prompt/actions-commit-hash@v3    
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag fscojr/nginx:$IMAGE_TAG
      env:
        IMAGE_TAG:  ${{ steps.commit.outputs.short }}

    - name: Build the Docker image
      run: docker push fscojr/nginx:$IMAGE_TAG
      env:
        IMAGE_TAG: ${{ steps.commit.outputs.short }}
    outputs:
      commit: ${{ steps.commit.outputs.short }}

  cid:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
      name: Checkout code app

    - uses: actions/checkout@v4
      name: Checkout code charts
      with:
        repository: 'fscojr/apps-charts'
    
    - name: Update Charts
      env:
        IMAGE_TAG: ${{ needs.build.outputs.commit }}
      run: echo $IMAGE_TAG

    - name: list
      run: |
        ls -l
        ls -l ../
    
